import bcrypt from 'bcryptjs';

const demoPasswordHash = bcrypt.hashSync('Password123!', 10);

export const users = [
  {
    id: 'u-admin',
    name: 'Ephraim',
    email: 'gyaneeugenia@gmail.com',
    passwordHash: demoPasswordHash,
    role: 'SYSTEM_ADMIN',
    department: 'Executive Secretary',
    title: 'System Administrator',
    avatar: 'E'
  },
  {
    id: 'u-abena-espm',
    name: 'Abena',
    email: 'geniaetornam@gmail.com',
    passwordHash: demoPasswordHash,
    role: 'NORMAL_USER',
    department: 'Energy Services and Performance Monitoring',
    title: 'Monitoring Officer',
    avatar: 'A'
  },
  {
    id: 'u-es-records',
    name: 'Ama Mensah',
    email: 'registry@purc.gov',
    passwordHash: demoPasswordHash,
    role: 'NORMAL_USER',
    department: 'Executive Secretary',
    title: 'Records Officer',
    avatar: 'AM'
  }
];

export const departments = [
  { id: 'd-executive-secretary', code: 'ES', name: 'Executive Secretary', head: '', status: 'ACTIVE' },
  { id: 'd-reg-economics', code: 'RED', name: 'Regulatory Economics', head: '', status: 'ACTIVE' },
  { id: 'd-energy-monitoring', code: 'ESPM', name: 'Energy Services and Performance Monitoring', head: '', status: 'ACTIVE' },
  { id: 'd-water-monitoring', code: 'WSPM', name: 'Water Services and Performance Monitoring', head: '', status: 'ACTIVE' },
  { id: 'd-regional-operations', code: 'ROD', name: 'Regional Operations', head: '', status: 'ACTIVE' },
  { id: 'd-legal', code: 'LS', name: 'Legal Services', head: '', status: 'ACTIVE' },
  { id: 'd-finance', code: 'FA', name: 'Finance and Administration', head: '', status: 'ACTIVE' }
];

export const letters = [
  {
    id: 'in-001',
    trackingNumber: 'PURC/ES/ESPM/2026-04/111',
    type: 'INCOMING',
    status: 'ES_RECEIVED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-04',
    receivedAt: '2026-04-04T09:15:00.000Z',
    createdAt: '2026-04-04T09:15:00.000Z',
    registryNumber: '1',
    letterNumber: '1',
    subject: 'Request for Data on Electricity Cost',
    senderOrganization: 'Electricity Company of Ghana',
    sender: 'Managing Director, Electricity Company of Ghana',
    recipient: 'Cecil Oduro Nyarko',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'ES office',
    assignedTo: '',
    remarks: 'Received at ES through Natasha, Front Desk. Not yet dispatched.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-002',
    trackingNumber: 'PURC/ES/RED/2026-04/124',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-04-07',
    receivedAt: '2026-04-07T10:20:00.000Z',
    dispatchedAt: '2026-04-07T15:05:00.000Z',
    createdAt: '2026-04-07T10:20:00.000Z',
    updatedAt: '2026-04-07T15:05:00.000Z',
    registryNumber: '2',
    letterNumber: '2',
    subject: 'Request for clarification on 2026 tariff adjustment',
    senderOrganization: 'Northern Electricity Distribution Company',
    sender: 'Northern Electricity Distribution Company',
    recipient: 'Executive Secretary',
    routeDepartment: 'Regulatory Economics',
    currentDepartment: 'Regulatory Economics',
    assignedTo: '',
    remarks: 'Dispatched from ES to Regulatory Economics for tariff review.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-003',
    trackingNumber: 'PURC/ES/WSPM/2026-04/139',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-11',
    receivedAt: '2026-04-11T08:45:00.000Z',
    dispatchedAt: '2026-04-11T12:30:00.000Z',
    createdAt: '2026-04-11T08:45:00.000Z',
    updatedAt: '2026-04-12T09:10:00.000Z',
    registryNumber: '3',
    letterNumber: '3',
    subject: 'Submission of water quality monitoring returns',
    senderOrganization: 'Ghana Water Company Limited',
    sender: 'Ghana Water Company Limited',
    recipient: 'Executive Secretary',
    routeDepartment: 'Water Services and Performance Monitoring',
    currentDepartment: 'Water Services and Performance Monitoring',
    assignedTo: '',
    remarks: 'Dispatched from ES to Water Services and Performance Monitoring. Received by department on April 12, 2026.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-004',
    trackingNumber: 'PURC/ES/ROD/2026-04/158',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'URGENT',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-04-16',
    receivedAt: '2026-04-16T13:05:00.000Z',
    dispatchedAt: '2026-04-16T16:20:00.000Z',
    createdAt: '2026-04-16T13:05:00.000Z',
    updatedAt: '2026-04-16T16:20:00.000Z',
    registryNumber: '4',
    letterNumber: '4',
    subject: 'Consumer petition on estimated billing in Tamale',
    senderOrganization: 'Northern Region Consumer Group',
    sender: 'Northern Region Consumer Group',
    recipient: 'Executive Secretary',
    routeDepartment: 'Regional Operations',
    currentDepartment: 'Regional Operations',
    assignedTo: '',
    remarks: 'Urgent petition dispatched from ES to Regional Operations for regional follow-up.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-005',
    trackingNumber: 'PURC/ES/LS/2026-04/172',
    type: 'INCOMING',
    status: 'ES_RECEIVED',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-21',
    receivedAt: '2026-04-21T11:30:00.000Z',
    createdAt: '2026-04-21T11:30:00.000Z',
    registryNumber: '5',
    letterNumber: '5',
    subject: 'Request for legal opinion on licence condition',
    senderOrganization: 'Association of Independent Power Producers',
    sender: 'Association of Independent Power Producers',
    recipient: 'Executive Secretary',
    routeDepartment: 'Legal Services',
    currentDepartment: 'ES office',
    assignedTo: '',
    dueAt: '2026-06-05',
    remarks: 'Received at ES office and awaiting dispatch to Legal Services.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-006',
    trackingNumber: 'PURC/ES/FA/2026-04/189',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'LOW',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-27',
    receivedAt: '2026-04-27T14:10:00.000Z',
    dispatchedAt: '2026-04-28T09:00:00.000Z',
    createdAt: '2026-04-27T14:10:00.000Z',
    updatedAt: '2026-04-28T09:00:00.000Z',
    registryNumber: '6',
    letterNumber: '6',
    subject: 'Invoice submission for stakeholder workshop logistics',
    senderOrganization: 'BlueGate Conference Services',
    sender: 'BlueGate Conference Services',
    recipient: 'Executive Secretary',
    routeDepartment: 'Finance and Administration',
    currentDepartment: 'Finance and Administration',
    assignedTo: '',
    remarks: 'Dispatched from ES to Finance and Administration for payment verification.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-007',
    trackingNumber: 'PURC/ES/ESPM/2026-05/204',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-05-04',
    receivedAt: '2026-05-04T09:35:00.000Z',
    dispatchedAt: '2026-05-04T13:40:00.000Z',
    createdAt: '2026-05-04T09:35:00.000Z',
    updatedAt: '2026-05-05T08:50:00.000Z',
    registryNumber: '7',
    letterNumber: '7',
    subject: 'Quarterly electricity reliability performance report',
    senderOrganization: 'Ghana Grid Company Limited',
    sender: 'Ghana Grid Company Limited',
    recipient: 'Energy Services and Performance Monitoring',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'Energy Services and Performance Monitoring',
    assignedTo: '',
    remarks: 'Dispatched from ES to ESPM. Received by department for technical review.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  },
  {
    id: 'in-008',
    trackingNumber: 'PURC/ES/WSPM/2026-05/218',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-05-08',
    receivedAt: '2026-05-08T10:10:00.000Z',
    dispatchedAt: '2026-05-08T14:25:00.000Z',
    createdAt: '2026-05-08T10:10:00.000Z',
    updatedAt: '2026-05-08T14:25:00.000Z',
    registryNumber: '8',
    letterNumber: '8',
    subject: 'Water service interruption report for Nsawam',
    senderOrganization: 'Community Water and Sanitation Agency',
    sender: 'Community Water and Sanitation Agency',
    recipient: 'Executive Secretary',
    routeDepartment: 'Water Services and Performance Monitoring',
    currentDepartment: 'Water Services and Performance Monitoring',
    assignedTo: '',
    remarks: 'Dispatched from ES to Water Services and Performance Monitoring for service quality review.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-009',
    trackingNumber: 'PURC/ES/RED/2026-05/232',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-11',
    receivedAt: '2026-05-11T08:25:00.000Z',
    dispatchedAt: '2026-05-11T11:45:00.000Z',
    createdAt: '2026-05-11T08:25:00.000Z',
    updatedAt: '2026-05-12T10:00:00.000Z',
    registryNumber: '9',
    letterNumber: '9',
    subject: 'Natural gas cost data for tariff computation',
    senderOrganization: 'Ghana National Gas Company',
    sender: 'Ghana National Gas Company',
    recipient: 'Executive Secretary',
    routeDepartment: 'Regulatory Economics',
    currentDepartment: 'Regulatory Economics',
    assignedTo: '',
    remarks: 'Dispatched from ES to Regulatory Economics. Received by department for tariff model update.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-010',
    trackingNumber: 'PURC/ES/ESPM/2026-05/247',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'URGENT',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-05-15',
    receivedAt: '2026-05-15T15:05:00.000Z',
    dispatchedAt: '2026-05-15T16:55:00.000Z',
    createdAt: '2026-05-15T15:05:00.000Z',
    updatedAt: '2026-05-15T16:55:00.000Z',
    registryNumber: '10',
    letterNumber: '10',
    subject: 'Urgent notice on transformer overload at Pokuase',
    senderOrganization: 'Electricity Company of Ghana',
    sender: 'Electricity Company of Ghana',
    recipient: 'Executive Secretary',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'Energy Services and Performance Monitoring',
    assignedTo: '',
    remarks: 'Urgent technical letter dispatched from ES to ESPM for immediate monitoring action.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  },
  {
    id: 'in-011',
    trackingNumber: 'PURC/ES/ROD/2026-05/263',
    type: 'INCOMING',
    status: 'ES_RECEIVED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-05-19',
    receivedAt: '2026-05-19T09:50:00.000Z',
    createdAt: '2026-05-19T09:50:00.000Z',
    registryNumber: '11',
    letterNumber: '11',
    subject: 'Regional office request for complaint mediation support',
    senderOrganization: 'PURC Ashanti Regional Office',
    sender: 'PURC Ashanti Regional Office',
    recipient: 'Executive Secretary',
    routeDepartment: 'Regional Operations',
    currentDepartment: 'ES office',
    assignedTo: '',
    dueAt: '2026-06-03',
    remarks: 'Received at ES office. Not yet dispatched to Regional Operations.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-012',
    trackingNumber: 'PURC/ES/FA/2026-05/279',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-22',
    receivedAt: '2026-05-22T12:15:00.000Z',
    dispatchedAt: '2026-05-22T15:20:00.000Z',
    createdAt: '2026-05-22T12:15:00.000Z',
    updatedAt: '2026-05-22T15:20:00.000Z',
    registryNumber: '12',
    letterNumber: '12',
    subject: 'Budget request for public education campaign',
    senderOrganization: 'Public Affairs Unit',
    sender: 'Public Affairs Unit',
    recipient: 'Executive Secretary',
    routeDepartment: 'Finance and Administration',
    currentDepartment: 'Finance and Administration',
    assignedTo: '',
    remarks: 'Dispatched from ES to Finance and Administration for budget advice.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-013',
    trackingNumber: 'PURC/ES/LS/2026-05/291',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-05-26',
    receivedAt: '2026-05-26T08:40:00.000Z',
    dispatchedAt: '2026-05-26T13:15:00.000Z',
    createdAt: '2026-05-26T08:40:00.000Z',
    updatedAt: '2026-05-26T13:15:00.000Z',
    registryNumber: '13',
    letterNumber: '13',
    subject: 'Draft memorandum of understanding for utility data sharing',
    senderOrganization: 'Ministry of Energy',
    sender: 'Ministry of Energy',
    recipient: 'Executive Secretary',
    routeDepartment: 'Legal Services',
    currentDepartment: 'Legal Services',
    assignedTo: '',
    remarks: 'Dispatched from ES to Legal Services for review of draft MOU clauses.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-014',
    trackingNumber: 'PURC/ES/WSPM/2026-05/306',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'URGENT',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-28',
    receivedAt: '2026-05-28T14:35:00.000Z',
    dispatchedAt: '2026-05-28T16:10:00.000Z',
    createdAt: '2026-05-28T14:35:00.000Z',
    updatedAt: '2026-05-29T09:05:00.000Z',
    registryNumber: '14',
    letterNumber: '14',
    subject: 'Urgent complaint on low water pressure in Cape Coast',
    senderOrganization: 'Cape Coast Residents Association',
    sender: 'Cape Coast Residents Association',
    recipient: 'Executive Secretary',
    routeDepartment: 'Water Services and Performance Monitoring',
    currentDepartment: 'Water Services and Performance Monitoring',
    assignedTo: '',
    remarks: 'Urgent complaint dispatched from ES to WSPM. Received by department for investigation.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'in-015',
    trackingNumber: 'PURC/ES/ESPM/2026-06/318',
    type: 'INCOMING',
    status: 'DISPATCHED_TO_DEPARTMENT',
    priority: 'LOW',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-06-01',
    receivedAt: '2026-06-01T08:55:00.000Z',
    dispatchedAt: '2026-06-01T11:05:00.000Z',
    createdAt: '2026-06-01T08:55:00.000Z',
    updatedAt: '2026-06-01T11:05:00.000Z',
    registryNumber: '15',
    letterNumber: '15',
    subject: 'Monthly power outage schedule notification',
    senderOrganization: 'Northern Electricity Distribution Company',
    sender: 'Northern Electricity Distribution Company',
    recipient: 'Executive Secretary',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'Energy Services and Performance Monitoring',
    assignedTo: '',
    remarks: 'Dispatched from ES to ESPM for monitoring and record update.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  },
  {
    id: 'out-001',
    trackingNumber: 'PURC/ES/OUT/2026-04/201',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-05',
    dispatchedAt: '2026-04-05T10:30:00.000Z',
    createdAt: '2026-04-05T09:10:00.000Z',
    updatedAt: '2026-04-05T10:30:00.000Z',
    registryNumber: '16',
    letterNumber: '16',
    subject: 'Acknowledgement of electricity cost data request',
    sender: 'Energy Services and Performance Monitoring',
    recipient: 'Electricity Company of Ghana',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'Electricity Company of Ghana',
    assignedTo: '',
    remarks: 'Dispatched from PURC to Electricity Company of Ghana and logged by ES.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  },
  {
    id: 'out-002',
    trackingNumber: 'PURC/ES/OUT/2026-04/215',
    type: 'OUTGOING',
    status: 'READY_FOR_SIGNATURE',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-04-10',
    createdAt: '2026-04-10T14:00:00.000Z',
    registryNumber: '17',
    letterNumber: '17',
    subject: 'Draft response on tariff adjustment clarification',
    sender: 'Regulatory Economics',
    recipient: 'Northern Electricity Distribution Company',
    routeDepartment: 'Regulatory Economics',
    currentDepartment: 'ES office',
    assignedTo: '',
    dueAt: '2026-06-06',
    remarks: 'Ready for ES signature before external dispatch to NEDCo.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-003',
    trackingNumber: 'PURC/ES/OUT/2026-04/229',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-15',
    dispatchedAt: '2026-04-15T11:25:00.000Z',
    createdAt: '2026-04-15T09:45:00.000Z',
    updatedAt: '2026-04-15T11:25:00.000Z',
    registryNumber: '18',
    letterNumber: '18',
    subject: 'Request for corrected water quality dataset',
    sender: 'Water Services and Performance Monitoring',
    recipient: 'Ghana Water Company Limited',
    routeDepartment: 'Water Services and Performance Monitoring',
    currentDepartment: 'Ghana Water Company Limited',
    assignedTo: '',
    remarks: 'Dispatched from PURC to Ghana Water Company Limited for corrected returns.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-004',
    trackingNumber: 'PURC/ES/OUT/2026-04/244',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'URGENT',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-04-20',
    dispatchedAt: '2026-04-20T16:35:00.000Z',
    createdAt: '2026-04-20T12:15:00.000Z',
    updatedAt: '2026-04-20T16:35:00.000Z',
    registryNumber: '19',
    letterNumber: '19',
    subject: 'Directive on estimated billing complaint investigation',
    sender: 'Regional Operations',
    recipient: 'PURC Northern Regional Office',
    routeDepartment: 'Regional Operations',
    currentDepartment: 'PURC Northern Regional Office',
    assignedTo: '',
    remarks: 'Urgent outgoing letter dispatched from PURC to the Northern Regional Office.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-005',
    trackingNumber: 'PURC/ES/OUT/2026-04/257',
    type: 'OUTGOING',
    status: 'READY_FOR_SIGNATURE',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-04-25',
    createdAt: '2026-04-25T10:05:00.000Z',
    registryNumber: '20',
    letterNumber: '20',
    subject: 'Legal review request for licence condition',
    sender: 'Legal Services',
    recipient: 'Association of Independent Power Producers',
    routeDepartment: 'Legal Services',
    currentDepartment: 'ES office',
    assignedTo: '',
    remarks: 'Ready for ES signature before dispatch to the Association of Independent Power Producers.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-006',
    trackingNumber: 'PURC/ES/OUT/2026-04/271',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'LOW',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-04-30',
    dispatchedAt: '2026-04-30T15:15:00.000Z',
    createdAt: '2026-04-30T11:25:00.000Z',
    updatedAt: '2026-04-30T15:15:00.000Z',
    registryNumber: '21',
    letterNumber: '21',
    subject: 'Payment processing acknowledgement',
    sender: 'Finance and Administration',
    recipient: 'BlueGate Conference Services',
    routeDepartment: 'Finance and Administration',
    currentDepartment: 'BlueGate Conference Services',
    assignedTo: '',
    remarks: 'Dispatched from PURC to vendor after Finance and Administration verification.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-007',
    trackingNumber: 'PURC/ES/OUT/2026-05/286',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-05-03',
    dispatchedAt: '2026-05-03T13:30:00.000Z',
    createdAt: '2026-05-03T10:40:00.000Z',
    updatedAt: '2026-05-03T13:30:00.000Z',
    registryNumber: '22',
    letterNumber: '22',
    subject: 'Request for grid reliability supporting data',
    sender: 'Energy Services and Performance Monitoring',
    recipient: 'Ghana Grid Company Limited',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'Ghana Grid Company Limited',
    assignedTo: '',
    remarks: 'Dispatched from PURC to Ghana Grid Company Limited for reliability data confirmation.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  },
  {
    id: 'out-008',
    trackingNumber: 'PURC/ES/OUT/2026-05/299',
    type: 'OUTGOING',
    status: 'READY_FOR_SIGNATURE',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-09',
    createdAt: '2026-05-09T09:20:00.000Z',
    registryNumber: '23',
    letterNumber: '23',
    subject: 'Draft response on Nsawam water service interruption',
    sender: 'Water Services and Performance Monitoring',
    recipient: 'Community Water and Sanitation Agency',
    routeDepartment: 'Water Services and Performance Monitoring',
    currentDepartment: 'ES office',
    assignedTo: '',
    remarks: 'Ready for ES signature before dispatch to Community Water and Sanitation Agency.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-009',
    trackingNumber: 'PURC/ES/OUT/2026-05/313',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-05-13',
    dispatchedAt: '2026-05-13T14:45:00.000Z',
    createdAt: '2026-05-13T11:05:00.000Z',
    updatedAt: '2026-05-13T14:45:00.000Z',
    registryNumber: '24',
    letterNumber: '24',
    subject: 'Acknowledgement of natural gas tariff data',
    sender: 'Regulatory Economics',
    recipient: 'Ghana National Gas Company',
    routeDepartment: 'Regulatory Economics',
    currentDepartment: 'Ghana National Gas Company',
    assignedTo: '',
    remarks: 'Dispatched from PURC to Ghana National Gas Company after Regulatory Economics review.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-010',
    trackingNumber: 'PURC/ES/OUT/2026-05/326',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'URGENT',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-16',
    dispatchedAt: '2026-05-16T09:55:00.000Z',
    createdAt: '2026-05-16T08:30:00.000Z',
    updatedAt: '2026-05-16T09:55:00.000Z',
    registryNumber: '25',
    letterNumber: '25',
    subject: 'Emergency monitoring request on Pokuase transformer overload',
    sender: 'Energy Services and Performance Monitoring',
    recipient: 'Electricity Company of Ghana',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'Electricity Company of Ghana',
    assignedTo: '',
    remarks: 'Urgent outgoing letter dispatched from PURC to ECG for immediate technical update.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  },
  {
    id: 'out-011',
    trackingNumber: 'PURC/ES/OUT/2026-05/342',
    type: 'OUTGOING',
    status: 'READY_FOR_SIGNATURE',
    priority: 'LOW',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-05-20',
    createdAt: '2026-05-20T16:05:00.000Z',
    registryNumber: '26',
    letterNumber: '26',
    subject: 'Mediation support letter for Ashanti regional complaint',
    sender: 'Regional Operations',
    recipient: 'PURC Ashanti Regional Office',
    routeDepartment: 'Regional Operations',
    currentDepartment: 'ES office',
    assignedTo: '',
    remarks: 'Ready for ES signature before dispatch to PURC Ashanti Regional Office.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-012',
    trackingNumber: 'PURC/ES/OUT/2026-05/357',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-24',
    dispatchedAt: '2026-05-24T12:20:00.000Z',
    createdAt: '2026-05-24T09:45:00.000Z',
    updatedAt: '2026-05-24T12:20:00.000Z',
    registryNumber: '27',
    letterNumber: '27',
    subject: 'Budget concurrence for public education campaign',
    sender: 'Finance and Administration',
    recipient: 'Public Affairs Unit',
    routeDepartment: 'Finance and Administration',
    currentDepartment: 'Public Affairs Unit',
    assignedTo: '',
    remarks: 'Dispatched from PURC to Public Affairs Unit after Finance and Administration advice.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-013',
    trackingNumber: 'PURC/ES/OUT/2026-05/369',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'HIGH',
    confidentiality: 'INTERNAL',
    attachments: 2,
    letterDate: '2026-05-27',
    dispatchedAt: '2026-05-27T15:40:00.000Z',
    createdAt: '2026-05-27T11:10:00.000Z',
    updatedAt: '2026-05-27T15:40:00.000Z',
    registryNumber: '28',
    letterNumber: '28',
    subject: 'Legal comments on utility data sharing MOU',
    sender: 'Legal Services',
    recipient: 'Ministry of Energy',
    routeDepartment: 'Legal Services',
    currentDepartment: 'Ministry of Energy',
    assignedTo: '',
    remarks: 'Dispatched from PURC to Ministry of Energy after Legal Services review.',
    createdBy: 'Ama Mensah',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-014',
    trackingNumber: 'PURC/ES/OUT/2026-05/384',
    type: 'OUTGOING',
    status: 'DISPATCHED',
    priority: 'URGENT',
    confidentiality: 'INTERNAL',
    attachments: 1,
    letterDate: '2026-05-30',
    dispatchedAt: '2026-05-30T10:35:00.000Z',
    createdAt: '2026-05-30T08:50:00.000Z',
    updatedAt: '2026-05-30T10:35:00.000Z',
    registryNumber: '29',
    letterNumber: '29',
    subject: 'Directive on Cape Coast low water pressure complaint',
    sender: 'Water Services and Performance Monitoring',
    recipient: 'Ghana Water Company Limited',
    routeDepartment: 'Water Services and Performance Monitoring',
    currentDepartment: 'Ghana Water Company Limited',
    assignedTo: '',
    remarks: 'Urgent outgoing letter dispatched from PURC to Ghana Water Company Limited.',
    createdBy: 'Ephraim',
    createdByDepartment: 'Executive Secretary'
  },
  {
    id: 'out-015',
    trackingNumber: 'PURC/ES/OUT/2026-06/399',
    type: 'OUTGOING',
    status: 'READY_FOR_SIGNATURE',
    priority: 'NORMAL',
    confidentiality: 'INTERNAL',
    attachments: 0,
    letterDate: '2026-06-01',
    createdAt: '2026-06-01T13:10:00.000Z',
    registryNumber: '30',
    letterNumber: '30',
    subject: 'Acknowledgement of NEDCo power outage schedule',
    sender: 'Energy Services and Performance Monitoring',
    recipient: 'Northern Electricity Distribution Company',
    routeDepartment: 'Energy Services and Performance Monitoring',
    currentDepartment: 'ES office',
    assignedTo: '',
    remarks: 'Ready for ES signature before dispatch to NEDCo.',
    createdBy: 'Abena',
    createdByDepartment: 'Energy Services and Performance Monitoring'
  }
];

function movementDate(letter, offsetMinutes = 0) {
  const base = new Date(letter.updatedAt || letter.dispatchedAt || letter.receivedAt || letter.createdAt);
  base.setMinutes(base.getMinutes() + offsetMinutes);
  return base.toISOString();
}

function registrationMovement(letter) {
  return {
    id: `mv-${letter.id}-registered`,
    letterId: letter.id,
    title: 'Letter registered',
    actor: letter.createdBy,
    department: letter.createdByDepartment,
    status: 'CURRENT',
    at: letter.createdAt,
    note: 'Record created'
  };
}

function dispatchMovement(letter) {
  if (!['DISPATCHED_TO_DEPARTMENT', 'DISPATCHED'].includes(letter.status)) return null;
  return {
    id: `mv-${letter.id}-dispatched`,
    letterId: letter.id,
    title: letter.type === 'INCOMING' ? `Dispatched to ${letter.routeDepartment}` : 'Outgoing letter dispatched',
    actor: letter.createdBy,
    department: letter.type === 'INCOMING' ? letter.routeDepartment : letter.currentDepartment,
    status: 'CURRENT',
    at: letter.dispatchedAt || movementDate(letter, 10),
    note: letter.type === 'INCOMING'
      ? `Dispatched from ES to ${letter.routeDepartment}`
      : `Dispatched from PURC to ${letter.recipient}`
  };
}

export const movements = letters
  .flatMap((letter) => [registrationMovement(letter), dispatchMovement(letter)])
  .filter(Boolean)
  .sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime());

export const notifications = [];

export const auditLogs = letters
  .map((letter) => ({
    id: `audit-${letter.id}`,
    action: 'LETTER_CREATED',
    actor: letter.createdBy,
    entity: letter.trackingNumber,
    severity: 'INFO',
    at: letter.createdAt,
    ip: '127.0.0.1'
  }))
  .sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime());

// Two statuses only: every received (incoming) letter is RECEIVED, every
// outgoing letter is DISPATCHED. Normalise the sample records on load.
letters.forEach((letter) => {
  letter.status = letter.type === 'OUTGOING' ? 'DISPATCHED' : 'RECEIVED';
});
